### PR TITLE
Track devicesettings from lineage

### PR DESCRIPTION
**Pull request by marshmello61**
Signed-off-by: marshmello61 <ultramayur123@gmail.com>

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
I don't get it. What's the difference?

**Comment by marshmello61** [comment]
Nothing but the proper. Nvm I'm really dumb sometimes

**Comment by NurKeinNeid** [comment]
Nah, all good. It is intentional that I do not mix the additions with the existing repos. I want to be visible which repos are additional and which are only replaced.

**Comment by marshmello61** [comment]
I understand

**Pull request closed without merging**
